services:
  api:
    build: ./server
    ports: ["8000:8000"]
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./client
    ports: ["5173:5173"]
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_healthy
