services:
  api:
    build: ./server
    ports: ["8080:8080"]
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./client
    ports: ["3000:3000"]
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      api:
        condition: service_healthy
